# Generated by Django 6.0.1 on 2026-01-23 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_renter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tlf',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
