# Generated by Django 6.0.1 on 2026-01-24 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='tlf',
            new_name='phone',
        ),
    ]
