# Generated by Django 6.0.1 on 2026-01-28 01:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_tlf_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=14, validators=[django.core.validators.RegexValidator(message='Enter a valid PT number in next format (+351)999999999 or +351999999999 or 999999999', regex='^(\\+351|\\(\\+351\\))?9\\d{8}$')]),
        ),
    ]
