# Generated by Django 6.0.1 on 2026-01-28 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='end_data',
            new_name='end_data',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='start_data',
            new_name='start_data',
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('CONFIRMED', 'CONFIRMED'), ('REJECTED', 'REJECTED'), ('CANCELED', 'CANCELED')], default='PENDING', max_length=10),
        ),
    ]
