# Generated by Django 6.0.1 on 2026-01-24 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_rename_categories_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('city', models.CharField(choices=[('LIS', 'Lisbon'), ('OPO', 'Porto'), ('VNG', 'Vila Nova de Gaia'), ('SIN', 'Sintra'), ('CAS', 'Cascais'), ('AMA', 'Amadora'), ('COI', 'Coimbra'), ('BRA', 'Braga'), ('SET', 'Setúbal'), ('AVE', 'Aveiro'), ('FAO', 'Faro'), ('GUI', 'Guimarães'), ('VIS', 'Viseu'), ('LEI', 'Leiria'), ('EVO', 'Évora'), ('PRM', 'Portimão'), ('FNC', 'Funchal')], default='LIS', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='items.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='itemImages')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='items.item')),
            ],
        ),
    ]
